# Generated by Django 3.1.6 on 2021-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, verbose_name='Question')),
                ('responce', models.CharField(blank=True, max_length=250, verbose_name='Responce')),
            ],
        ),
    ]
