# Generated by Django 3.1.6 on 2021-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='responce',
            field=models.CharField(max_length=250, verbose_name='Responce'),
        ),
    ]
